# Знакомство с PyTorch

## Введение

Библиотека PyTorch является универсальным инструментом машинного обучения. Она популярна работе с нейронными сетями. Является open-source проектом. В библиотеке есть четыре ключевых составляющих:

* Развитый инструментарий для работы с тензорами. Он похож на numpy, но даёт дополнительные возможности по контролю выделяемой памяти, что важно при работе с большими моделями и данными.

* Простое построение динамического вычислительного графа, позволяющего получать градиенты целевых функций от параметров модели.

* Большой набор готовых слоёв для построения нейронных сетей произвольной архитектуры.

* Возможность перенаправлять вычисления на графические процессоры GPU.


In [17]:
import torch
import numpy as np

In [18]:
e  = torch.eye(3) # единичная матрица 3x3
print(e) 

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


## Тензоры

Тензор - это основной объект в *PyTorch*. Тензоры схожи с *ndarrays* в *NumPy*, с добавлением того, что тензоры могут быть использованы на GPU для ускорения вычислений.

* Тензор - это набор из элементов одного типа. 
* Тензоры могут быть одномерные (векторы), двумерные (матрицы), трехмерные и так далее - любой размерности.

In [7]:
a = torch.rand(5, 3) # сгенерировали матрицу 5x3 из случайных чисел
a

tensor([[0.3685, 0.4806, 0.1398],
        [0.3450, 0.8511, 0.5468],
        [0.1013, 0.8532, 0.9164],
        [0.7567, 0.5744, 0.2798],
        [0.7790, 0.6205, 0.5533]])

In [8]:
a.shape # посмотрели размеры

torch.Size([5, 3])

In [9]:
a + 3 # добавили 3 ко всем элементам

tensor([[3.3685, 3.4806, 3.1398],
        [3.3450, 3.8511, 3.5468],
        [3.1013, 3.8532, 3.9164],
        [3.7567, 3.5744, 3.2798],
        [3.7790, 3.6205, 3.5533]])

## Вычисления на видеокарте

Если на компьютере есть графическая карта, то можно осуществлять вычисления на ней - обычно это ускоряет вычисления в разы.

Проведем эксперимент:
1. Сначала создадим две единичных матрицы большой размерности и перемножим их как обычно, используя мощности центрального процессора (CPU), засечем время.

2. Затем создадим такие же тензоры, перенесем их на GPU, там сделаем умножение и вернем результат на CPU (можно сразу создавать тензоры на GPU, но обычно придерживаются первого варианта). Также замерим время и сравним.

**Первый вариант (CPU)**

In [12]:
%%time

x1 = torch.eye(10000)
y1 = torch.eye(10000)
z1 = x1.mm(y1)   

CPU times: total: 1min 20s
Wall time: 19 s


**Второй вариант (GPU)**

In [14]:
cpu = torch.device("cpu")
gpu = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

In [15]:
%%time

x1 = torch.eye(10000).to(gpu)
y1 = torch.eye(10000).to(gpu)
z1 = x1.mm(y1).to(cpu)

CPU times: total: 1min 20s
Wall time: 20.5 s


## Сравнение PyTorch и NumPy
[Torch for Numpy users](https://github.com/torch/torch7/wiki/Torch-for-Numpy-users)

Операции в PyTorch и NumPy очень похожи.

Давайте посмотрим на пару примеров:

1) создадим матрицы случайных чисел в NumPy и в PyTorch:
NumPy: a = np.random.rand(5, 3)
PyTorch: x = torch.rand(5, 3)

2) умножим матрицу на себя транспонированную:
NumPy: np.dot(a, a.T)
PyTorch: x.mm(x.t())

3) посчитаем среднее значение матрицы по столбцам:
NumPy: a.mean(axis=-1)
PyTorch: x.mean(dim=-1)

In [20]:
# numpy
# 1) создадим матрицы случайных чисел в NumPy и в PyTorch
a = np.random.rand(5, 3)
a

array([[0.65746899, 0.9790198 , 0.38225826],
       [0.51968344, 0.4987433 , 0.03126495],
       [0.99861941, 0.47712412, 0.04358963],
       [0.88381713, 0.04219248, 0.10862971],
       [0.83888688, 0.61318873, 0.03288338]])

In [21]:
# PyTorch
# 1) создадим матрицы случайных чисел в NumPy и в PyTorch
x = torch.rand(5, 3)
x

tensor([[0.1485, 0.8491, 0.9799],
        [0.5552, 0.6038, 0.6151],
        [0.5755, 0.6739, 0.1658],
        [0.4044, 0.9084, 0.5454],
        [0.4928, 0.5718, 0.9918]])

In [22]:
# NumPy
# 2) умножим матрицу на себя транспонированную
np.dot(a, a.T)

array([[1.53686662, 0.8419066 , 1.14033775, 0.66391423, 1.16443596],
       [0.8419066 , 0.51979326, 0.75829126, 0.48374464, 0.74280749],
       [1.14033775, 0.75829126, 1.22678821, 0.90746312, 1.13172923],
       [0.66391423, 0.48374464, 0.90746312, 0.79471333, 0.77086666],
       [1.16443596, 0.74280749, 1.13172923, 0.77086666, 1.08081294]])

In [23]:
# PyTorch
# 2) умножим матрицу на себя транспонированную
x.mm(x.t())

tensor([[1.7032, 1.1979, 0.8201, 1.3659, 1.5306],
        [1.1979, 1.0513, 0.8284, 1.1086, 1.2290],
        [0.8201, 0.8284, 0.8127, 0.9353, 0.8333],
        [1.3659, 1.1086, 0.9353, 1.2863, 1.2597],
        [1.5306, 1.2290, 0.8333, 1.2597, 1.5535]])

In [24]:
# 3) посчитаем среднее значение матрицы по столбцам
a.mean(axis=-1)

array([0.67291568, 0.34989723, 0.50644439, 0.34487977, 0.49498633])

In [25]:
x.mean(dim=-1)

tensor([0.6592, 0.5914, 0.4717, 0.6194, 0.6855])