# Знакомство с PyTorch

Сейчас мы познакомимся с библиотекой *PyTorch*. Он очень похож на *NumPy*, и сейчас вы в этом убедитесь!

А почему именно *PyTorch*? Почитать можно [здесь](https://habr.com/ru/post/334380/).

## Вспоминаем *NumPy* и сравниваем операции в *PyTorch*

In [9]:
from torchvision import models

In [10]:
dir(models)

['AlexNet',
 'AlexNet_Weights',
 'ConvNeXt',
 'ConvNeXt_Base_Weights',
 'ConvNeXt_Large_Weights',
 'ConvNeXt_Small_Weights',
 'ConvNeXt_Tiny_Weights',
 'DenseNet',
 'DenseNet121_Weights',
 'DenseNet161_Weights',
 'DenseNet169_Weights',
 'DenseNet201_Weights',
 'EfficientNet',
 'EfficientNet_B0_Weights',
 'EfficientNet_B1_Weights',
 'EfficientNet_B2_Weights',
 'EfficientNet_B3_Weights',
 'EfficientNet_B4_Weights',
 'EfficientNet_B5_Weights',
 'EfficientNet_B6_Weights',
 'EfficientNet_B7_Weights',
 'EfficientNet_V2_L_Weights',
 'EfficientNet_V2_M_Weights',
 'EfficientNet_V2_S_Weights',
 'GoogLeNet',
 'GoogLeNetOutputs',
 'GoogLeNet_Weights',
 'Inception3',
 'InceptionOutputs',
 'Inception_V3_Weights',
 'MNASNet',
 'MNASNet0_5_Weights',
 'MNASNet0_75_Weights',
 'MNASNet1_0_Weights',
 'MNASNet1_3_Weights',
 'MaxVit',
 'MaxVit_T_Weights',
 'MobileNetV2',
 'MobileNetV3',
 'MobileNet_V2_Weights',
 'MobileNet_V3_Large_Weights',
 'MobileNet_V3_Small_Weights',
 'RegNet',
 'RegNet_X_16GF_Weights'

Мы можем создавать матрицы, перемножать их, складывать, транспонировать и в целом совершать любые матричные операции

In [11]:
import numpy as np 

import torch
import torchvision

import torch.nn as nn
import torch.nn.functional as F

import matplotlib.pyplot as plt

In [12]:
np.random.seed(42)

a = np.random.rand(5, 3) # создали случайную матрицу 
a

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452],
       [0.05808361, 0.86617615, 0.60111501],
       [0.70807258, 0.02058449, 0.96990985],
       [0.83244264, 0.21233911, 0.18182497]])

In [13]:
print("Проверили размеры : %s\n" % (a.shape,))

Проверили размеры : (5, 3)



In [14]:
print("Добавили 5 :\n%s\n" % (a + 5))

Добавили 5 :
[[5.37454012 5.95071431 5.73199394]
 [5.59865848 5.15601864 5.15599452]
 [5.05808361 5.86617615 5.60111501]
 [5.70807258 5.02058449 5.96990985]
 [5.83244264 5.21233911 5.18182497]]



## Задание

Умножьте матрицу `а` на транспонированную матрицу `а`.  

Чему равен самый первый элемент результата?  
Ответ округлите до сотых.

In [17]:
t = np.dot(a, a.T)
t = np.round(t, 2)
t

array([[1.58, 0.49, 1.29, 0.99, 0.65],
       [0.49, 0.41, 0.26, 0.58, 0.56],
       [1.29, 0.26, 1.11, 0.64, 0.34],
       [0.99, 0.58, 0.64, 1.44, 0.77],
       [0.65, 0.56, 0.34, 0.77, 0.77]])

In [18]:
print("Среднее по колонкам :\n%s\n" % (a.mean(axis=-1)))

Среднее по колонкам :
[0.68574946 0.30355721 0.50845826 0.56618897 0.40886891]



In [19]:
print("Изменили размеры :\n%s\n" % (a.reshape(3, 5).shape,))

Изменили размеры :
(3, 5)



## Задание

При помощи *NumPy* посчитайте сумму квадратов натуральных чисел от 1 до 10000.

In [35]:
import numpy as np

a = range(1, 10)
a

range(1, 10)

In [39]:
b = np.arange(1,11)
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
sum = 0
for i in list(range(1, 10001)):
    sum += i ** 2

print(sum)

333383335000


In [63]:
sum = 1
for i in np.arange(1, 10001, dtype=np.int64):
    sum += i ** 2

print(sum)

333383335001


### Аналогичные операции в *PyTorch* выглядят следующим образом, синтаксис отличается, но совсем немного:

In [65]:
x = torch.rand(5, 3)
x

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411]])

In [66]:
print("Проверили размеры : %s\n" % (x.shape,))

Проверили размеры : torch.Size([5, 3])



In [67]:
print("Добавили 5 :\n%s\n" % (x + 5))

Добавили 5 :
tensor([[5.8823, 5.9150, 5.3829],
        [5.9593, 5.3904, 5.6009],
        [5.2566, 5.7936, 5.9408],
        [5.1332, 5.9346, 5.5936],
        [5.8694, 5.5677, 5.7411]])



In [68]:
print("X*X^T  (1):\n%s\n" % (torch.matmul(x, x.transpose(1, 0))))
print("X*X^T  (2):\n%s\n" % (x.mm(x.t())))

X*X^T  (1):
tensor([[1.7622, 1.4337, 1.3127, 1.1999, 1.5702],
        [1.4337, 1.4338, 1.1213, 0.8494, 1.5010],
        [1.3127, 1.1213, 1.5807, 1.3343, 1.3708],
        [1.1999, 0.8494, 1.3343, 1.2435, 1.0863],
        [1.5702, 1.5010, 1.3708, 1.0863, 1.6274]])

X*X^T  (2):
tensor([[1.7622, 1.4337, 1.3127, 1.1999, 1.5702],
        [1.4337, 1.4338, 1.1213, 0.8494, 1.5010],
        [1.3127, 1.1213, 1.5807, 1.3343, 1.3708],
        [1.1999, 0.8494, 1.3343, 1.2435, 1.0863],
        [1.5702, 1.5010, 1.3708, 1.0863, 1.6274]])



In [52]:
print("Среднее по колонкам :\n%s\n" % (x.mean(dim=-1)))

Среднее по колонкам :
tensor([0.3080, 0.3459, 0.6385, 0.5080, 0.3934])



In [64]:
print("Изменили размеры :\n%s\n" % (x.view([3, 5]).shape,))
print("Изменили размеры :\n%s\n" % (x.view_as(x.t()).shape,))

Изменили размеры :
torch.Size([3, 5])

Изменили размеры :
torch.Size([3, 5])



Небольшой пример того, как меняются операции:

* `x.reshape([1,2,8]) -> x.view(1,2,8)`

* `x.sum(axis=-1) -> x.sum(dim=-1)`

* `x.astype('int64') -> x.type(torch.LongTensor)`

Для помощи вам есть [таблица](https://github.com/torch/torch7/wiki/Torch-for-Numpy-users), которая поможет вам найти аналог операции в *NumPy*.


При помощи *PyTorch* посчитаем сумму квадратов натуральных чисел от 1 до 10000.

In [69]:
torch.sum(torch.range(1, 10000) ** 2)

C:\Users\HOME\AppData\Local\Temp\ipykernel_6428\3730827553.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.sum(torch.range(1, 10000) ** 2)


tensor(3.3338e+11)

## Создаем тензоры в *PyTorch* и снова изучаем базовые операции

In [70]:
x = torch.empty(5, 3) # пустой тензор
print(x)

tensor([[7.0909e+02, 8.9823e-43, 7.0909e+02],
        [8.9823e-43, 7.0909e+02, 8.9823e-43],
        [7.0909e+02, 8.9823e-43, 7.0909e+02],
        [8.9823e-43, 7.0909e+02, 8.9823e-43],
        [7.0909e+02, 8.9823e-43, 7.0909e+02]])


In [71]:
x = torch.rand(5, 3) # тензор со случайными числами
print(x)

tensor([[0.4294, 0.8854, 0.5739],
        [0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317],
        [0.1053, 0.2695, 0.3588],
        [0.1994, 0.5472, 0.0062]])


In [73]:
# np.int64 = torch.LongTensor
x = torch.zeros(5, 3, dtype=torch.long) # тензор с нулями и указанием типов чисел
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [75]:
x = torch.tensor([5.5, 3]) # конструируем тензор из питоновского листа
print(x)

tensor([5.5000, 3.0000])


In [76]:
x = x.new_ones(5, 3, dtype=torch.double) # используем уже созданный тензор для создания тензора из единичек
print(x, x.size()) 

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64) torch.Size([5, 3])


In [60]:
x = torch.randn_like(x, dtype=torch.float) # создаем матрицу с размерами как у x
print(x, x.size())

tensor([[ 0.9023,  1.1222,  0.8512],
        [ 1.1030, -0.5384, -0.0357],
        [ 1.2008,  0.7556,  0.0645],
        [-1.4366, -1.2169,  0.6574],
        [ 0.9912, -1.5123,  0.9068]]) torch.Size([5, 3])


## Задание

Сгенерируйте два тензора: `x` и `y` размера 5 на 3 со случайными числами.
Вычислите сумму тензоров `x` и `y`.

В ответе напишите значение первой координаты в полученной суммы, округленной до сотых.

In [88]:
torch.manual_seed(42)
x = torch.rand(5, 3)
x

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411]])

In [89]:
torch.round(torch.tensor(x[0]), decimals=2)

C:\Users\HOME\AppData\Local\Temp\ipykernel_6428\3207709343.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  torch.round(torch.tensor(x[0]), decimals=2)


tensor([0.8800, 0.9200, 0.3800])

In [79]:
y = torch.rand(5, 3)
y

tensor([[0.4294, 0.8854, 0.5739],
        [0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317],
        [0.1053, 0.2695, 0.3588],
        [0.1994, 0.5472, 0.0062]])

In [90]:
torch.round(torch.tensor(y[0]), decimals=2)

C:\Users\HOME\AppData\Local\Temp\ipykernel_6428\119967581.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  torch.round(torch.tensor(y[0]), decimals=2)


tensor([0.4300, 0.8900, 0.5700])

In [91]:
print(x * y) # поэлементное умножение

tensor([[0.3789, 0.8102, 0.2197],
        [0.2557, 0.2450, 0.1620],
        [0.1132, 0.2356, 0.7824],
        [0.0140, 0.2519, 0.2130],
        [0.1733, 0.3106, 0.0046]])


## Задание

Умножьте матрицу `x` на транспонированную матрицу `y`.

В ответ напишите последний элемент (правый нижний) полученной матрицы.  
Ответ округлите до сотых.

In [93]:
print("x*x^T  (option 1):\n%s\n" % (torch.matmul(x, x.transpose(1, 0))))
print("x*x^T  (option 2):\n%s\n" % (x.mm(x.t())))

x*x^T  (option 1):
tensor([[1.7622, 1.4337, 1.3127, 1.1999, 1.5702],
        [1.4337, 1.4338, 1.1213, 0.8494, 1.5010],
        [1.3127, 1.1213, 1.5807, 1.3343, 1.3708],
        [1.1999, 0.8494, 1.3343, 1.2435, 1.0863],
        [1.5702, 1.5010, 1.3708, 1.0863, 1.6274]])

x*x^T  (option 2):
tensor([[1.7622, 1.4337, 1.3127, 1.1999, 1.5702],
        [1.4337, 1.4338, 1.1213, 0.8494, 1.5010],
        [1.3127, 1.1213, 1.5807, 1.3343, 1.3708],
        [1.1999, 0.8494, 1.3343, 1.2435, 1.0863],
        [1.5702, 1.5010, 1.3708, 1.0863, 1.6274]])



In [94]:
print("y*y^T  (option 1):\n%s\n" % (torch.matmul(y, y.transpose(1, 0))))
print("y*y^T  (option 2):\n%s\n" % (y.mm(y.t())))

y*y^T  (option 1):
tensor([[1.2978, 0.8248, 0.9297, 0.4898, 0.5737],
        [0.8248, 0.5375, 0.5282, 0.2939, 0.3981],
        [0.9297, 0.5282, 0.9747, 0.4249, 0.2556],
        [0.4898, 0.2939, 0.4249, 0.2125, 0.1707],
        [0.5737, 0.3981, 0.2556, 0.1707, 0.3392]])

y*y^T  (option 2):
tensor([[1.2978, 0.8248, 0.9297, 0.4898, 0.5737],
        [0.8248, 0.5375, 0.5282, 0.2939, 0.3981],
        [0.9297, 0.5282, 0.9747, 0.4249, 0.2556],
        [0.4898, 0.2939, 0.4249, 0.2125, 0.1707],
        [0.5737, 0.3981, 0.2556, 0.1707, 0.3392]])



In [95]:
print(x.unsqueeze(0).shape) # добавили измерение в начало, аналог броадкастинга 

torch.Size([1, 5, 3])


In [96]:
print(x.unsqueeze(0).squeeze(0).shape) # убрали измерение в начале, аналог броадкастинга 

torch.Size([5, 3])


In [100]:
a = torch.rand((1, 3))
a

tensor([[0.4414, 0.2969, 0.8317]])

In [101]:
a.squeeze(0)

tensor([0.4414, 0.2969, 0.8317])

Мы также можем делать обычные срезы и переводить матрицы назад в *NumPy*:

In [102]:
a = np.ones((3, 5))
x = torch.ones((3, 5))
print(np.allclose(x.numpy(), a))
print(np.allclose(x.numpy()[:, 1], a[:, 1]))

True
True


In [103]:
a = np.array([1,2,3,4])
b = np.array([[5],[6],[7],[8]])

a.shape, b.shape

((4,), (4, 1))

In [104]:
a @ b

array([70])

In [105]:
b @ a

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 1)